kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: aws-ebs-csi-driver
  labels:
    firefly.ai/argo: applications
    firefly.ai/application: aws-ebs-csi-driver
    firefly.ai/cluster: product
    firefly.ai/project: default
spec:
  project: default
  sources:
    - repoURL: "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
      chart: "aws-ebs-csi-driver"
      targetRevision: "2.28.1"
      helm:
        releaseName: aws-ebs-csi-driver
        valueFiles:
          - $values/argocd/releases/infrastructure/aws-ebs-csi-driver.yaml
    - repoURL: "https://github.com/infralight/product-projects"
      targetRevision: "HEAD"
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "aws-ebs-csi-driver"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=orphan
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
