apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    repository: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/infralight/product-projects.git
    path: argocd/releases/infrastructure/external-secrets
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true