# Base image
FROM python:3.10

# Copy application code
COPY /src /src
WORKDIR /src

# Install dependencies
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libcurl4-openssl-dev libssl-dev curl
RUN pip install pycurl
RUN pip install -r requirements.txt


# Run application
CMD ["python", "main.py"]
