apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'aws-load-balancer-controller'
      server: '*'
    - namespace: 'external-dns'
      server: '*'
    - namespace: 'external-secrets'
      server: '*'
    - namespace: 'argocd'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'